language: python
python:
  - 3.5
  - 3.6
install:
  - pip install -U pip
  - pip install --progress-bar off -r requirements.txt
  - pip install --progress-bar off nose

script:
  - pip install .
  - nosetests tests
  - detect-blobs --help
  - collect-patches --help
  - eflash-train --help